name: mlat
channels:
  - conda-forge
dependencies:
  # 基础
  - python=3.11                    # 与基础镜像对齐
  - numpy
  - matplotlib
  - pillow
  - tqdm
  - jupyterlab                     # notebook 会随 jlab 4+ 自动拉 notebook 7
  - ipykernel

  # PyTorch（CPU 版）
  - pytorch=2.2.*=cpu*             # 或直接用 pytorch-cpu
  - torchvision
